<?php

namespace App\Console\Commands;

use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class CreateAccountant extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'accountant:create
                            {--name= : The accountant\'s full name}
                            {--email= : The accountant\'s email address}
                            {--firm= : The accounting firm name}
                            {--phone= : The accountant\'s phone number}
                            {--password= : The login password (auto-generated if not provided)}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new accountant user for the platform. Used when deploying to a new client company.';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $this->info('');
        $this->info('╔══════════════════════════════════════════╗');
        $this->info('║     🏢 Create New Accountant User       ║');
        $this->info('╚══════════════════════════════════════════╝');
        $this->info('');

        // Gather inputs (use flags or prompt interactively)
        $name = $this->option('name') ?: $this->ask('Full name');
        $email = $this->option('email') ?: $this->ask('Email address');
        $firmName = $this->option('firm') ?: $this->ask('Firm name');
        $phone = $this->option('phone') ?: $this->ask('Phone number (optional)', '');
        $password = $this->option('password');
        $autoGeneratedPassword = false;

        // Auto-generate a secure password if not provided
        if (empty($password)) {
            $password = Str::password(16);
            $autoGeneratedPassword = true;
        }

        // Validate inputs
        $validator = Validator::make([
            'name' => $name,
            'email' => $email,
            'firm_name' => $firmName,
            'password' => $password,
        ], [
            'name' => 'required|string|max:255',
            'email' => 'required|email|max:255',
            'firm_name' => 'required|string|max:255',
            'password' => 'required|string|min:8',
        ]);

        if ($validator->fails()) {
            $this->error('Validation failed:');
            foreach ($validator->errors()->all() as $error) {
                $this->line("  ✗ {$error}");
            }
            return self::FAILURE;
        }

        // Check if email already exists
        $existingUser = User::where('email', $email)->first();
        if ($existingUser) {
            if (!$this->confirm("A user with email '{$email}' already exists. Do you want to update their account to accountant?")) {
                $this->info('Operation cancelled.');
                return self::SUCCESS;
            }

            $existingUser->update([
                'name' => $name,
                'firm_name' => $firmName,
                'phone' => $phone ?: $existingUser->phone,
                'role' => 'accountant',
                'setup_completed' => true,
                'email_verified_at' => now(),
                'password' => Hash::make($password),
            ]);

            $user = $existingUser;
            $this->info('✓ Existing user updated to accountant role.');
        } else {
            $user = User::create([
                'name' => $name,
                'email' => $email,
                'role' => 'accountant',
                'firm_name' => $firmName,
                'phone' => $phone ?: null,
                'device_token' => Str::random(64),
                'setup_completed' => true,
                'email_verified_at' => now(),
                'password' => Hash::make($password),
            ]);

            $this->info('✓ New accountant user created successfully.');
        }

        // Display credentials
        $this->info('');
        $this->info('┌──────────────────────────────────────────┐');
        $this->info('│         📋 Login Credentials             │');
        $this->info('├──────────────────────────────────────────┤');
        $this->table(
            ['Field', 'Value'],
            [
                ['Name', $user->name],
                ['Email', $user->email],
                ['Firm', $user->firm_name],
                ['Password', $autoGeneratedPassword ? $password : '(as provided)'],
                ['Role', 'accountant'],
            ]
        );

        if ($autoGeneratedPassword) {
            $this->warn('');
            $this->warn('⚠  The password above was auto-generated. Share it securely');
            $this->warn('   with the accountant and advise them to change it after login.');
        }

        $this->info('');
        $this->info('The accountant can now log in at the application URL.');
        $this->info('');

        return self::SUCCESS;
    }
}
